#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "PHASE26_STATUS=ready"

echo "AVAILABLE_ARTIFACTS:"
echo "BOARD_DECK=FND/WORKCAPTAIN_BOARD_DECK_SOURCE.md"
echo "INVESTOR_DECK=FND/WORKCAPTAIN_INVESTOR_DECK_SOURCE.md"
echo "ENTERPRISE_QA=FND/WORKCAPTAIN_ENTERPRISE_DILIGENCE_QA_MATRIX.md"
echo "SOVEREIGN_PACK=FND/WORKCAPTAIN_SOVEREIGN_BRIEFING_PACK.md"
echo "TRACEABILITY_MAP=FND/WORKCAPTAIN_PRESENTATION_TRACEABILITY_MAP.md"
